export const beers = [
  'Artus',
  'Atak Chmielu',
  'Piwo biłgorajskie',
  'Barkas',
  'Black Boss Porter',
  'Bosman',
  'Bracki Grand Champion Birofilia 2011',
  'Bracki Koźlak Dubeltowy',
  'Bracki Rauchbock',
  'Brackie',
  'Brackie Mastne',
  'Brackie Pale Ale belgijskie',
  'Brok',
  'Captain Jack',
  'Carmèll',
  'Core Beer',
  'Cornelius Weizen Bier',
  'Czarny Smok',
  'Dębowe Mocne',
  'Dog in the Fog',
  'EB',
  'Fortuna Czarne',
  'Frater',
  'Gdańskie',
  'Gingers',
  'Goolman',
  'Grand Imperial Porter',
  'Piwo grodziskie',
  'Harnaś',
  'Heban',
  'Hevelius',
  'Kaper',
  'Karmi',
  'Kasztelan',
  'Koźlak (browar Amber)',
  'Królewskie',
  'Książ',
  'Kujawiak',
  'Lech',
  'Leżajsk',
  'Lwówek Książęcy',
  'Łomża',
  'Magnus',
  'Miodowmazowieckie',
  'Mocny Full',
  'Noteckie',
  'Okocim',
  'Perła',
  'Piast',
  'Piwo jopejskie',
  'Porter warmiński',
  'Racibor',
  'Redd’s',
  'Specjal',
  'Strong',
  'Tatra',
  'Tyskie',
  'Warka',
  'Wiśnia w piwie',
  'Wojak',
  'Zwierzyniec',
  'Żubr',
  'Żywe',
  'Żywiec',
  'Żywiec Porter'
];